version: "3.8"
services:
  server:
    container_name: server
    image: python:3.10
    build: ./server
    ports:
    - published: 5000
      target: 5000
      protocol: tcp
  animal:
    container_name: animal
    image: python:3.10
    build: ./animal_api
    ports:
    - published: 5000
      target: 5000
      protocol: tcp